import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ReactElement } from "react";
import ResponsiveAppBar from "../../layout/appbar";
import { NextPageWithLayout } from "./_app";

const inter = Inter({ subsets: ["latin"] });

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by Navigating through the Nav-Component&nbsp;
            <code className={styles.code}>NavBaar</code>
          </p>
          <div>
            <Image
              src="https://www.freepnglogos.com/uploads/pok-mon-go-logo-png-30.png"
              width="200"
              height="200"
              alt="Pokémon GO Logo png"
            />
          </div>
        </div>

        <div className={styles.center}>
          <Image
            src="https://www.freepnglogos.com/uploads/black-pokemon-logo-transparent-27.png"
            width="200"
            height="200"
            alt="Black Pokemon Logo Transparent"
          />
        </div>

       
      </main>
    </>
  );
};
Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      {" "}
      <ResponsiveAppBar />
      {page}
    </>
  );
};
export default Page;
